index.html

Adicionado Uma task em Concluded e uma em Progress, e retirei duas tasks do backlog

Adicionando e movendo tasks

---

index.html

Estou movendo os cards de estudo de programação básica e HTML e CSS básico para a coluna de concluded e adicionando os cards de estudo de javascript básico e react básico na coluna backlog

adicionando card feature 001, 002, 003, 004

---

index.html

Modificações:
Atualização de cards. 
Card do curso 'linguagem de programação básica' movida para 'Concluded'
Card do curso 'javascript básico ao avançado' movido para 'In progress'.

Atualização dos cards de progresso 

---

index.html

Criando um novo card chamado: FEAT022 - JavaScript para páginas dinâminas, na sessão do backlog.

Criando o card feat022 - javascript para paginas dinaminas no backlog

---

index.html

Atualizei o FEAT001 como concluído e estou adicionando os cards novos na coluna "In Progress" - FEAT002 , e FEAT003 na coluna do "Backlog".

Atualizando FEAT001 e Adicionando FEAT002 e FEAT003

---

db/pedro-oliveira/tasks.js
scripts/loadTasks.js

adiciona o card da tarefa curso de java

adicionando novo card java

---

db/caroline-andrade/tasks.js
scripts/loadTasks.js

Estou adicionando um card novo para o curso de spring boot 3 na coluna de backlog.

Adicionando card feature curso de spring boot 3

---

db/pedro-oliveira/tasks.js

Adicionando novo card no back logo, estudar inglês

feature: adicionando novo card (backlog)

---

db/andre-pereira/tasks.js
scripts/loadTasks.js

Estou adicionando dois novos cards para o board.

Adicionando card de git e html/css

---

db/artur-lucas/tasks.js
scripts/loadTasks.js

Estou adicionando 3 cards para o board.

Adicinando card de Artur Lucas

---

db/pedro-oliveira/tasks.js

adicionando o card do desafio do restaurante ao backlog

feat: adicionando card desafio do restaurante

---

db/pedro-oliveira/tasks.js

adicionando card, desafio do cv da aula01

feat: adicionando card do desafio do cv

---

db/pablo-miranda/tasks.js
scripts/loadTasks.js

Adicionado 2 cards com as seguintes tarefas da aula 01:
1. Currículo, in_progress
2. Landing page, backlog

Cards com os desafios da aula01

---

db/pedro-oliveira/tasks.js

trocando o status do card "desafio do cv" para concluded

feat: trocando status do card (desafio do cv) para concluded

---

db/daniela-barreto/tasks.js

Estou adicionando um novo card para o board, na aba backlog.

Adicionando card do desafio do cv

---

db/daniela-barreto/tasks.js

Estou adicionando um novo card para o board, na aba backlog.

Adicionando card do desafio do site de um restaurante/lanchonete

---

db/luisa-silva/tasks.js
scripts/loadTasks.js

Estou criando um novo db e atualizando meus cards com estudos e projetos recentes.  Adicionei um novo card do curso de android que estou fazendo, dois novos cards, do projeto passado pelo professor de produzir uma lading page de um restaurante e de um curso de git/github, que realizei e um novo card de um curso de react que desejo fazer.

adicionando-novos-cards

---

db/tatiane-fontes/tasks.js
scripts/loadTasks.js

Estou adicionando 3 novos cards:  praticar git, melhorando currículo e  desenvolvendo site.

Adicionando 3 novos cards  

---

db/pedro-oliveira/tasks.js

trocando status do card site restaurante para in progress

feat: trocando status do card site restaurante para in progess

---

db/luisa-silva/tasks.js

Estou adicionando novos cards ao board.

adicionando-cards-estudos-projeto01

---

db/brasimar-henrique/tasks.js
scripts/loadTasks.js

Assistindo aulas atrasadas: atualização do repositório, revisão JS, HTML e CSS

 Atualizando list team members/Add card

---

db/luiz-reis/tasks.js
scripts/loadTasks.js

Estou adicionando dois novos cards para o board.

Adicionando os cards

---

db/alik-breno/task.js
scripts/loadTasks.js

Estou adicionando um card no board

Adicionando card do desafio do resstaurante

---

db/sarah-bichler/tasks.js
scripts/loadTasks.js

Estou adicionando três novos cards para o board

Adicionando card de Java, e desafios cv e restaurante

---

db/sarah-bichler/tasks.js
scripts/loadTasks.js

Atualizar meus cards

---

db/jucymara-lacet/tasks.js

Atualização dos cards dos desafios Currículo e Restaurante referentes à aula 01.
Modificação: Alocação dos cards de 'in_progress' para 'concluded'

Atualização cards dos desafios

---

db/jackeline-pereira/tasks.js
scripts/loadTasks.js

Adicionando novos cards em backlog

Adicionando novos cards em backlog

---

db/giordano-ferreira/tasks.js
scripts/loadTasks.js

Adicionando card de revisão conteúdo da aula01 e desenvolvimento desafios.

Adicionando novo card de revisão da aula01

---

db/daniela-barreto/tasks.js

Atualizando card do desafio do cv para concluded.

Atualizando card do desafio do cv

---

db/pedro-oliveira/tasks.js

adicionando card do deploy na vercel do desafio do restaurante

feat: adicionando card do deploy na vercel

---

db/thiago-andrade/tasks.js

Deploy site restaurante vercel

Adcionado deploy site restarante vercel

---

db/pablo-miranda/tasks.js

Realizado o deploy da landing page no Vercel: https://jullanar.vercel.app/

Deploy da landing page no Vercel, feito

---

db/jackeline-pereira/tasks.js

Atualizando card  desafio site para concluded

adicionando atualização de card

---

db/tatiane-fontes/tasks.js

Atualizando meus cards conforme evolução das tarefas

Atualiazação dos cards

---

db/priscilla-almeida/tasks.js
scripts/loadTasks.js

estou adicionando um novo card para aprofundar meus estudos de git e github

adicionando card de estudo de git

---

db/tatiane-fontes/tasks.js

Avançando nas atividades propostas e atualizando os cards

atualizando cards para concluded e in_progress

---

db/luiz-gonzaga/tasks.js
scripts/loadTasks.js

Estou adicionando 3 novos cards para o board.

Adicionando cards dos desafios da Aula01

---

db/pedro-oliveira/tasks.js

atualizando status do card vercel para concluded

feat: atualizando status do card vercel para concluded

---

db/jackeline-pereira/tasks.js

Adicionando card novo- Estudar inglês em backlog

Adicionando card novo- Estudar inglês

---

db/jucymara-lacet/tasks.js

Atualização de cards com adição de exercícios em JS referentes à aula 02.

Atualização cards

---

db/pedro-oliveira/tasks.js

adicionando card dos exercicios de js

feat: adicionando card dos exercicios de js

---

db/daniela-barreto/tasks.js

Adicionando e atualizando card de hospedar site para concluded.

Adicionando e atualizando card de hospedar site

---

db/pedro-oliveira/tasks.js

adicionando o link do repositorio a descricao do card

fix: adicionando o link do repositorio a descricao do card

---

db/daniela-barreto/tasks.js

Adicionando card de exercícios de JS para in progress.

Adicionando card de exercícios de JS

---

db/alik-breno/task.js
db/alik-breno/tasks.js

card adicionado do desafio das 150 questões de javascript de status in progress

new card in progress

---

db/luiz-gonzaga/tasks.js

Iniciando a resolução dos exercícios em JS .

Iniciando os exercicios JS

---

db/arrys-hanry/tasks.js
scripts/loadTasks.js

adicionando um novo card sobre os exercicios de JS em progresso

novo card sobre o desafio exercicio de JS

---

db/jackeline-pereira/tasks.js

Inserindo novo card de estudo em JS e card de atividade em JS que foram inseridas no classroom.

Atualizando e inserindo novos cards ao board

---

db/pablo-miranda/tasks.js

Adicionada nova task de React a ser terminada até QUINTA!

Novo card com task de react
